
# This is a YAML file. It is used to store configuration data.

input: ../data/input.txt

output: ../data/output.txt



grid:
    Lx: 10
    Ly: 10
    #eps: 1e-7

lists:
    dJUs:
        start: 0.01
        stop: 0.6
        step: 0.01
physics:
    N: 10
    dJU: 0.1
    muU: "np.sqrt(2) - 1"
    UIB: 0.2
    cutoff: 5


