
# This is a YAML file. It is used to store configuration data.

input: ../data/input.txt

output: ../data/output.txt

max_iter_psi: 5000

grid:
    N: 10
    Lx: 10
    Ly: 10
    #eps: 1e-7

physics:
    Mu: "np.sqrt(2) - 1"
    dJU:
        start: 0.01
        stop: 0.6
        step: 0.01
    UIB: 0.2


