
# This is a YAML file. It is used to store configuration data.

input: ../data/input.txt

output: ../data/output.txt


grid:
    Lx: 14 #10 sites in x
    Ly: 14 #10 # sites in y
    #eps: 1e-7

lists:
    dJUs:
        start: 0.0
        stop: 1
        num: 3 #200

    energies:
        start: 0.01
        stop: 0.35
        num: 3 # 200

physics:
    N: 7 #7 # Num of modes
    dJU: 0.1 # this is 2 * d * J, so 4J in 2D.
    muU: "np.sqrt(2) - 1"
    UIB: 0.2
    cutoff: 4 #4


